image: ayufan/rock64-dockerfiles:x86_64

stages:
  - build

variables:
  GITHUB_USER: ayufan-rock64
  GITHUB_REPO: chromium-overlay-rockpro64

  MANIFEST_BRANCH: release-R76-12239.B
  WORK_PATH: /data/chromiumos/$MANIFEST_BRANCH

# this requires GitLab Runner running in Privileged mode
image:
  before_script:
    - mkdir -p "$WORK_PATH"
    - useradd -u 1000 -g users -m -G sudo chronos
    - chown chronos:users "$WORK_PATH"
    - sudo -EHu chronos -- ./cros_init.sh "$WORK_PATH"
  script:
    - sudo -EHu chronos -- ./cros_run.sh "$WORK_PATH" ~/trunk/src/overlays/overlay-rockpro64/do_apply_patches.sh
    - sudo -EHu chronos -- ./cros_run.sh "$WORK_PATH" ~/trunk/src/overlays/overlay-rockpro64/do_release_and_publish.sh
  when: manual
  only:
    refs: [master]
